# TRABAJANDO LA GUÍA 05

### IMPORTAR LIBRERÍA Y CARGAR EL DATASET

In [1]:
# cargar pandas
import pandas as pd

In [2]:
# cargar el archivo de excel
df = pd.read_excel('riesgo_crediticio.xlsx')

### EXPLORACIÓN INICIAL

In [3]:
# mostrar la tabla
df

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
0,C001,60,1500.0,0,1000.0,1,5000.0,12,Alto
1,C002,26,8000.0,17,200.0,3,1000.0,6,Bajo
2,C003,25,2200.0,7,4000.0,0,5000.0,48,Medio
3,C004,61,5000.0,13,700.0,4,NaN,6,Bajo
4,C005,30,NaN,10,1000.0,0,5000.0,18,Bajo
...,...,...,...,...,...,...,...,...,...
75,C076,64,1200.0,3,2200.0,1,3000.0,48,Alto
76,C077,53,4200.0,1,4000.0,1,2000.0,24,Medio
77,C078,28,4200.0,16,4000.0,2,20000.0,36,Medio
78,C079,52,NaN,17,3000.0,0,20000.0,24,Medio
79,C080,36,2200.0,20,1000.0,4,5000.0,18,Medio

In [4]:
# mostrar las priera 10 filas del df
df.head(10)

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
0,C001,60,1500.0,0,1000.0,1,5000.0,12,Alto
1,C002,26,8000.0,17,200.0,3,1000.0,6,Bajo
2,C003,25,2200.0,7,4000.0,0,5000.0,48,Medio
3,C004,61,5000.0,13,700.0,4,NaN,6,Bajo
4,C005,30,NaN,10,1000.0,0,5000.0,18,Bajo
5,C006,26,1500.0,12,200.0,2,12000.0,36,Medio
6,C007,36,1200.0,14,4000.0,0,16000.0,6,Medio
7,C008,55,2600.0,20,NaN,1,2000.0,6,Medio
8,C009,62,2200.0,9,200.0,1,2000.0,24,Bajo
9,C010,37,4200.0,20,NaN,0,12000.0,18,Bajo

In [5]:
# mostrar las 10 útimas filas
df.tail(10)

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
70,C071,33,5000.0,15,400.0,0,NaN,36,Bajo
71,C072,62,8000.0,19,NaN,0,5000.0,48,Bajo
72,C073,42,2200.0,6,400.0,0,1000.0,12,Bajo
73,C074,50,6500.0,2,3000.0,3,5000.0,48,Medio
74,C075,64,NaN,15,2200.0,1,3000.0,48,Medio
75,C076,64,1200.0,3,2200.0,1,3000.0,48,Alto
76,C077,53,4200.0,1,4000.0,1,2000.0,24,Medio
77,C078,28,4200.0,16,4000.0,2,20000.0,36,Medio
78,C079,52,NaN,17,3000.0,0,20000.0,24,Medio
79,C080,36,2200.0,20,1000.0,4,5000.0,18,Medio

In [6]:
# mostrar 10 filas aleatorias
df.sample(10)

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
23,C024,25,1500.0,15,200.0,0,3000.0,48,Bajo
36,C037,30,NaN,15,3000.0,1,16000.0,6,Medio
16,C017,27,1800.0,20,400.0,3,2000.0,24,Medio
51,C052,51,2600.0,1,200.0,3,NaN,6,Alto
0,C001,60,1500.0,0,1000.0,1,5000.0,12,Alto
44,C045,65,3000.0,7,1000.0,3,3000.0,48,Medio
14,C015,36,1800.0,7,4000.0,1,16000.0,36,Alto
45,C046,61,2600.0,14,NaN,0,1000.0,24,Medio
28,C029,60,1200.0,7,200.0,0,12000.0,6,Medio
37,C038,30,NaN,0,2200.0,1,20000.0,18,Alto

In [7]:
# mostrar filas y columnas
df.shape

(80, 9)

In [8]:
# Mostrar los nombres de todas las columnas del DataFrame.
df.columns

Index(['cliente_id', 'edad', 'ingreso_mensual', 'antiguedad_laboral_anios',
       'deuda_mensual', 'atrasos_ultimos_12_meses', 'monto_solicitado',
       'plazo_meses', 'riesgo'],
      dtype='object')

In [9]:
# 8. Mostrar el tipo de dato de cada columna del DataFrame.
df.dtypes

cliente_id                   object
edad                          int64
ingreso_mensual             float64
antiguedad_laboral_anios      int64
deuda_mensual               float64
atrasos_ultimos_12_meses      int64
monto_solicitado            float64
plazo_meses                   int64
riesgo                       object
dtype: object

In [10]:
# 9. Mostrar la información general del DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cliente_id                80 non-null     object
 1   edad                      80 non-null     int64
 2   ingreso_mensual           73 non-null     float64
 3   antiguedad_laboral_anios  80 non-null     int64
 4   deuda_mensual             68 non-null     float64
 5   atrasos_ultimos_12_meses  80 non-null     int64
 6   monto_solicitado          68 non-null     float64
 7   plazo_meses               80 non-null     int64
 8   riesgo                    80 non-null     object
dtypes: float64(3), int64(4), object(2)
memory usage: 5.8+ KB

In [11]:
# 10. Mostrar los valores únicos de la columna "riesgo" del DataFrame
df['riesgo'].unique()

array(['Alto', 'Bajo', 'Medio'], dtype=object)

In [12]:
# 11. Mostrar los valores únicos de la columna "plazo_meses" del DataFrame
df['plazo_meses'].unique()

array([12,  6, 48, 18, 36, 24])

In [13]:
# 12.	Mostrar la cantidad de los valores únicos por cada columna del DataFrame
df.nunique()

cliente_id                  80
edad                        33
ingreso_mensual             10
antiguedad_laboral_anios    21
deuda_mensual                8
atrasos_ultimos_12_meses     5
monto_solicitado             7
plazo_meses                  6
riesgo                       3
dtype: int64

### SELECCIÓN DE COLUMNAS Y FILAS

In [14]:
# 13.	Mostrar las 3 primeras filas de las columnas "cliente_id" y "riesgo" del DataFrame.
df[0:4][["cliente_id","riesgo"]]

  cliente_id riesgo
0       C001   Alto
1       C002   Bajo
2       C003  Medio
3       C004   Bajo

In [15]:
# 14. Mostrar las filas de la posición 10 a la 15 (sin incluir la 15) de las columnas "cliente_id" y "edad".
df[10:15][["cliente_id","edad"]]

   cliente_id  edad
10       C011    33
11       C012    49
12       C013    34
13       C014    56
14       C015    36

In [16]:
# 15. Mostrar las filas pares desde la posición 0 hasta la 20 (sin incluir la 20), de las columnas "cliente_id", 
# "ingreso_mensual" y "riesgo".
df[0:20:2][["cliente_id","ingreso_mensual","riesgo"]]

   cliente_id  ingreso_mensual riesgo
0        C001           1500.0   Alto
2        C003           2200.0  Medio
4        C005              NaN   Bajo
6        C007           1200.0  Medio
8        C009           2200.0   Bajo
10       C011           8000.0   Bajo
12       C013           1200.0  Medio
14       C015           1800.0   Alto
16       C017           1800.0  Medio
18       C019           8000.0   Bajo

In [17]:
# 16. Mostrar las filas de la posición 20 a la 30 (incluir la 30) de las columnas "cliente_id", "edad" y "monto_solicitado".
df[20:31][["cliente_id","edad","monto_solicitado"]]

   cliente_id  edad  monto_solicitado
20       C021    26            3000.0
21       C022    30           20000.0
22       C023    27            5000.0
23       C024    25            3000.0
24       C025    50            5000.0
25       C026    64           20000.0
26       C027    48           12000.0
27       C028    57            2000.0
28       C029    60           12000.0
29       C030    52            3000.0
30       C031    56           16000.0

In [18]:
# 17. Mostrar las últimas 5 filas del DataFrame de las columnas "cliente_id" y "monto_solicitado".
#df[75:80][["cliente_id","monto_solicitado"]]

df[["cliente_id","monto_solicitado"]].tail(5)

   cliente_id  monto_solicitado
75       C076            3000.0
76       C077            2000.0
77       C078           20000.0
78       C079           20000.0
79       C080            5000.0

### FILTRADO DE CONDICIONES

In [19]:
# 18.Mostrar los clientes con "antiguedad_laboral_anios" es igual a 20.

df[df["antiguedad_laboral_anios"]==20]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
7,C008,55,2600.0,20,NaN,1,2000.0,6,Medio
9,C010,37,4200.0,20,NaN,0,12000.0,18,Bajo
16,C017,27,1800.0,20,400.0,3,2000.0,24,Medio
32,C033,23,8000.0,20,200.0,0,16000.0,48,Bajo
61,C062,37,3000.0,20,4000.0,3,12000.0,6,Alto
79,C080,36,2200.0,20,1000.0,4,5000.0,18,Medio

In [20]:
# 19. Mostrar los clientes con "edad" mayor a 62 años.

df[df["edad"]>62]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
25,C026,64,2200.0,9,2200.0,2,20000.0,36,Alto
44,C045,65,3000.0,7,1000.0,3,3000.0,48,Medio
53,C054,65,NaN,17,0.0,0,2000.0,48,Bajo
74,C075,64,NaN,15,2200.0,1,3000.0,48,Medio
75,C076,64,1200.0,3,2200.0,1,3000.0,48,Alto

In [21]:
# 20. Mostrar los clientes con "atrasos_ultimos_12_meses" igual a 2 o 4.

df[(df["atrasos_ultimos_12_meses"]==2) | (df["atrasos_ultimos_12_meses"]==4)]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
3,C004,61,5000.0,13,700.0,4,NaN,6,Bajo
5,C006,26,1500.0,12,200.0,2,12000.0,36,Medio
15,C016,42,3000.0,7,400.0,4,2000.0,6,Medio
18,C019,27,8000.0,17,1000.0,2,2000.0,18,Bajo
21,C022,30,5000.0,16,0.0,2,20000.0,6,Medio
25,C026,64,2200.0,9,2200.0,2,20000.0,36,Alto
30,C031,56,6500.0,15,700.0,4,16000.0,12,Medio
39,C040,23,6500.0,17,0.0,2,1000.0,6,Bajo
55,C056,22,2600.0,11,0.0,2,5000.0,48,Medio
59,C060,50,2200.0,6,3000.0,2,NaN,12,Alto
60,C061,34,1200.0,6,2200.0,2,NaN,6,Alto
69,C070,58,8000.0,10,3000.0,4,20000.0,48,Medio
77,C078,28,4200.0,16,4000.0,2,20000.0,36,Medio
79,C080,36,2200.0,20,1000.0,4,5000.0,18,Medio

In [22]:
# 21. Mostrar los clientes con "riesgo" "Alto" y "atrasos_ultimos_12_meses" mayor a 2.

df[(df["riesgo"]=="Alto") & (df["atrasos_ultimos_12_meses"]>2)]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
13,C014,56,3000.0,6,3000.0,3,20000.0,12,Alto
31,C032,26,1500.0,13,NaN,3,16000.0,24,Alto
51,C052,51,2600.0,1,200.0,3,NaN,6,Alto
61,C062,37,3000.0,20,4000.0,3,12000.0,6,Alto

In [23]:
# 22. Mostrar los clientes cuyo "ingreso_mensual" sea menor a 1500.

df[df["ingreso_mensual"]<1500]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
6,C007,36,1200.0,14,4000.0,0,16000.0,6,Medio
12,C013,34,1200.0,10,2200.0,1,2000.0,12,Medio
28,C029,60,1200.0,7,200.0,0,12000.0,6,Medio
60,C061,34,1200.0,6,2200.0,2,NaN,6,Alto
68,C069,55,1200.0,9,1000.0,1,16000.0,36,Alto
75,C076,64,1200.0,3,2200.0,1,3000.0,48,Alto

In [24]:
# 23. Mostrar los clientes con más de 19000 en "monto_solicitado".

df[df["monto_solicitado"]>19000]

,cliente_id,edad,ingreso_mensual,antiguedad_laboral_anios,deuda_mensual,atrasos_ultimos_12_meses,monto_solicitado,plazo_meses,riesgo
13,C014,56,3000.0,6,3000.0,3,20000.0,12,Alto
21,C022,30,5000.0,16,0.0,2,20000.0,6,Medio
25,C026,64,2200.0,9,2200.0,2,20000.0,36,Alto
33,C034,42,1500.0,7,700.0,1,20000.0,12,Medio
37,C038,30,NaN,0,2200.0,1,20000.0,18,Alto
52,C053,20,3000.0,4,1000.0,0,20000.0,36,Medio
69,C070,58,8000.0,10,3000.0,4,20000.0,48,Medio
77,C078,28,4200.0,16,4000.0,2,20000.0,36,Medio
78,C079,52,NaN,17,3000.0,0,20000.0,24,Medio

### CREACIÓN DE TABLAS RESUMEN / FRECUENCIA  -- INTERPRETACIÓN DE LOS RESULTADOS

In [25]:
# 24. Mostrar una tabla de frecuencias del "riesgo" de los clientes.

df["riesgo"].value_counts()

riesgo
Medio    39
Bajo     28
Alto     13
Name: count, dtype: int64

In [ ]:
# Interpretación
# La tabla muestra la distribución de los clientes según su nivel de riesgo. 
# De un total de 80 clientes, 39 presentan riesgo medio, 28 riesgo bajo y 13 riesgo alto.
# Por lo tanto, el nivel de riesgo más frecuente es el medio, mientras que el riesgo alto es el menos frecuente.

In [26]:
# 25. Mostrar una tabla de frecuencias del "plazo_meses" de los clientes.

df["plazo_meses"].value_counts()

plazo_meses
48    17
6     16
36    16
12    13
24    10
18     8
Name: count, dtype: int64

In [ ]:
# Interpretación
# La tabla muestra la distribución de los clientes según el plazo del crédito en meses. 
# El plazo más frecuente es de 48 meses, con 17 clientes, seguido de 6 y 36 meses, con 16 clientes cada uno.
# El plazo menos frecuente es de 18 meses, con 8 clientes. 
# En general, se observa que los clientes presentan distintos plazos de crédito, con una mayor frecuencia en los 48 meses.

In [27]:
# 26. Mostrar una tabla resumen del promedio del "ingreso_mensual", del "monto_solicitado" y de la "deuda_mensual" 
# agrupado por "riesgo".

df.groupby("riesgo")[["ingreso_mensual","monto_solicitado","deuda_mensual" ]].mean()

        ingreso_mensual  monto_solicitado  deuda_mensual
riesgo
Alto        1908.333333      13000.000000    2416.666667
Bajo        5119.230769       5136.363636     743.478261
Medio       3080.000000       9250.000000    1924.242424

In [ ]:
# Interpretación
# La tabla compara los promedios de ingreso mensual, monto solicitado y deuda mensual según el nivel de riesgo.
# Los clientes de riesgo alto presentan el menor ingreso mensual promedio (1908.33) y 
# la mayor deuda mensual promedio (2416.67). En cambio, 
# los clientes de riesgo bajo tienen el mayor ingreso mensual promedio (5119.23) y la menor deuda mensual promedio (743.48).
# Esto muestra que, en estos datos, un mayor nivel de riesgo está asociado con menores ingresos y mayores deudas mensuales.

In [29]:
# 27. Mostrar una tabla resumen del máximo de "monto_solicitado" y "ingreso_mensual" agrupado por "riesgo".

df.groupby("riesgo")[["monto_solicitado","ingreso_mensual"]].max()

        monto_solicitado  ingreso_mensual
riesgo
Alto             20000.0           3000.0
Bajo             16000.0           8000.0
Medio            20000.0           8000.0

In [ ]:
# Interpretación
# La tabla muestra los valores máximos del monto solicitado y del ingreso mensual para cada nivel de riesgo.
# Los clientes de riesgo alto alcanzan un monto solicitado máximo de 20 000 y un ingreso mensual máximo de 3 000. 
# En riesgo medio, el monto máximo también es 20 000, pero el ingreso máximo llega a 8 000. 
# En riesgo bajo, el monto máximo solicitado es 16 000 y el ingreso máximo es 8 000.
# Se observa que el grupo de riesgo alto presenta un ingreso máximo considerablemente menor que los otros niveles de riesgo, 
# aunque puede solicitar montos de crédito elevados.

In [30]:
# 28. Mostrar una tabla cruzada de frecuencias entre "riesgo" y "plazo_meses".Mostrar una tabla cruzada de frecuencias 
# entre "riesgo" y "atrasos_ultimos_12_meses".

pd.crosstab(df["riesgo"],df["atrasos_ultimos_12_meses"])

atrasos_ultimos_12_meses   0   1  2  3  4
riesgo
Alto                       1   5  3  4  0
Bajo                      16   6  2  3  1
Medio                     14  13  4  4  4

In [ ]:
# Interpretación
# La tabla muestra la cantidad de clientes según su nivel de riesgo y el número de atrasos en los últimos 12 meses.
# Se observa que los clientes de riesgo bajo y medio se concentran principalmente entre 0 y 1 atraso. 
# En cambio, en el grupo de riesgo alto predominan los clientes que presentan entre 1 y 3 atrasos.
# En general, los datos sugieren que una mayor cantidad de atrasos está asociada con un mayor nivel de riesgo crediticio.